version: '2'
services:
  db:
    image: mysql:5.7
    container_name: demo-db
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: web
        MYSQL_PASSWORD: webroot
        MYSQL_ROOT_HOST: '%'
    ports:
        - "3306:3306"
    volumes:
        - ./test.sql:/docker-entrypoint-initdb.d/test.sql
        - ./my-config.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
  web:
    image: webdevops/php:alpine
    container_name: demo-web
    volumes:
        - ./:/my-app/
    working_dir : /my-app/
    depends_on:
        - db
