version: '3'
services:
  db:
    image: mysql:5.7
    container_name: demo-db
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - ./qubiz.sql
  web:
    build: .
    container_name: demo-web
    depends_on:
    - db
